# Generated by Django 3.1.7 on 2021-03-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODOLIST', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='Task',
        ),
    ]
